In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sn

In [3]:
ESR = pd.read_csv('user_a.csv')
ESR.head()

Class  AF3 delta std  AF3 delta m  AF3 theta std  AF3 theta m  \
0    1.0    3569.164550  2063.892754       1.673726     4.444736   
1    1.0    3568.423670  2063.099248       1.897790     3.728823   
2    1.0    3568.157929  2062.445859       2.798014     2.574504   
3    1.0    3567.710021  2062.112673       2.181775     3.610507   
4    1.0    3565.546124  2063.128867       1.685161     3.384311   

   AF3 alpha std  AF3 alpha m  AF3 beta std  AF3 beta m  F7 delta std  ...  \
0       0.526209     3.002088      1.425022    3.302739   3563.803888  ...   
1       1.304186     1.854353      1.366575    2.546458   3563.560922  ...   
2       1.120537     1.958819      0.982433    2.258622   3563.279981  ...   
3       0.629608     2.155876      0.856275    2.233711   3562.787801  ...   
4       0.677526     1.795798      0.927924    1.909810   3562.655091  ...   

   F8 beta std  F8 beta m  AF4 delta std  AF4 delta m  AF4 theta std  \
0    45.468326  72.508750    3701.186330  2182.676835      18.192418   
1    36.551948  66.931186    3725.210509  2180.197439       8.820788   
2    40.754308  66.816547    3724.417296  2176.823208      18.159202   
3    38.074628  63.915386    3725.822160  2177.089059      19.737616   
4    35.357384  64.534645    3723.053978  2167.798335       8.429414   

   AF4 theta m  AF4 alpha std  AF4 alpha m  AF4 beta std  AF4 beta m  
0    41.349662      16.004756    42.046467     46.280843   73.565719  
1    38.012788      19.601233    29.431054     38.559351   67.470041  
2    23.612639      14.378291    19.555084     43.210004   67.781924  
3    29.484396      15.793034    25.713513     39.250246   65.031031  
4    26.374975      14.920736    35.675266     33.901687   66.956313  

[5 rows x 113 columns]

In [4]:
ESR

Class  AF3 delta std  AF3 delta m  AF3 theta std  AF3 theta m  \
0       1.0    3569.164550  2063.892754       1.673726     4.444736   
1       1.0    3568.423670  2063.099248       1.897790     3.728823   
2       1.0    3568.157929  2062.445859       2.798014     2.574504   
3       1.0    3567.710021  2062.112673       2.181775     3.610507   
4       1.0    3565.546124  2063.128867       1.685161     3.384311   
...     ...            ...          ...            ...          ...   
2875    0.0    3572.820630  2064.823341       0.676923     1.620879   
2876    0.0    3573.915291  2065.845542       0.860279     1.504333   
2877    0.0    3574.326202  2066.031013       1.416731     2.581577   
2878    0.0    3573.735788  2065.945333       1.119943     2.769816   
2879    0.0    3573.982930  2065.960401       1.011062     2.696217   

      AF3 alpha std  AF3 alpha m  AF3 beta std  AF3 beta m  F7 delta std  ...  \
0          0.526209     3.002088      1.425022    3.302739   3563.803888  ...   
1          1.304186     1.854353      1.366575    2.546458   3563.560922  ...   
2          1.120537     1.958819      0.982433    2.258622   3563.279981  ...   
3          0.629608     2.155876      0.856275    2.233711   3562.787801  ...   
4          0.677526     1.795798      0.927924    1.909810   3562.655091  ...   
...             ...          ...           ...         ...           ...  ...   
2875       0.965369     2.392263      2.582266    3.185588   3565.166724  ...   
2876       0.539180     1.331165      2.533695    2.870270   3565.734750  ...   
2877       0.715012     1.307975      2.261013    2.873613   3567.582880  ...   
2878       0.455408     1.541430      1.782814    3.067384   3567.857997  ...   
2879       1.021707     2.086820      1.922342    2.675613   3568.222662  ...   

      F8 beta std  F8 beta m  AF4 delta std  AF4 delta m  AF4 theta std  \
0       45.468326  72.508750    3701.186330  2182.676835      18.192418   
1       36.551948  66.931186    3725.210509  2180.197439       8.820788   
2       40.754308  66.816547    3724.417296  2176.823208      18.159202   
3       38.074628  63.915386    3725.822160  2177.089059      19.737616   
4       35.357384  64.534645    3723.053978  2167.798335       8.429414   
...           ...        ...            ...          ...            ...   
2875    26.247669  13.320391    3607.467804  2089.263161       1.605773   
2876    26.120266  14.809811    3613.165565  2089.298802       0.643899   
2877    26.513829  16.084048    3615.755534  2094.482958       1.851314   
2878    20.049092  21.248860    3620.821019  2097.450420       5.035767   
2879    19.210888  22.058247    3620.970803  2096.125026       4.120981   

      AF4 theta m  AF4 alpha std  AF4 alpha m  AF4 beta std  AF4 beta m  
0       41.349662      16.004756    42.046467     46.280843   73.565719  
1       38.012788      19.601233    29.431054     38.559351   67.470041  
2       23.612639      14.378291    19.555084     43.210004   67.781924  
3       29.484396      15.793034    25.713513     39.250246   65.031031  
4       26.374975      14.920736    35.675266     33.901687   66.956313  
...           ...            ...          ...           ...         ...  
2875     4.247634       1.649762     2.938868     31.019482   16.648758  
2876     6.903858       1.287563     3.942647     31.546882   17.429113  
2877     5.683580       2.411642     6.355117     32.238063   19.023897  
2878    12.027902       6.441267    14.663681     24.109509   26.468254  
2879    12.124434       7.613556    12.998119     23.635052   26.581116  

[2880 rows x 113 columns]

In [5]:
ESR.columns

Index(['Class', 'AF3 delta std', 'AF3 delta m', 'AF3 theta std', 'AF3 theta m',
       'AF3 alpha std', 'AF3 alpha m', 'AF3 beta std', 'AF3 beta m',
       'F7 delta std',
       ...
       'F8 beta std', 'F8 beta m', 'AF4 delta std', 'AF4 delta m',
       'AF4 theta std', 'AF4 theta m', 'AF4 alpha std', 'AF4 alpha m',
       'AF4 beta std', 'AF4 beta m'],
      dtype='object', length=113)

In [6]:
ESR.isnull().sum()  #isnull().sum()  gives the sum of missing value in the data set or  nan values here in the data set 


Class            0
AF3 delta std    0
AF3 delta m      0
AF3 theta std    0
AF3 theta m      0
                ..
AF4 theta m      0
AF4 alpha std    0
AF4 alpha m      0
AF4 beta std     0
AF4 beta m       0
Length: 113, dtype: int64

In [7]:
ESR.info() # gives the information about the data

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2880 entries, 0 to 2879
Columns: 113 entries, Class to AF4 beta m
dtypes: float64(113)
memory usage: 2.5 MB


In [8]:
ESR.tail(2881) #gives the entire description of the data set

Class  AF3 delta std  AF3 delta m  AF3 theta std  AF3 theta m  \
0       1.0    3569.164550  2063.892754       1.673726     4.444736   
1       1.0    3568.423670  2063.099248       1.897790     3.728823   
2       1.0    3568.157929  2062.445859       2.798014     2.574504   
3       1.0    3567.710021  2062.112673       2.181775     3.610507   
4       1.0    3565.546124  2063.128867       1.685161     3.384311   
...     ...            ...          ...            ...          ...   
2875    0.0    3572.820630  2064.823341       0.676923     1.620879   
2876    0.0    3573.915291  2065.845542       0.860279     1.504333   
2877    0.0    3574.326202  2066.031013       1.416731     2.581577   
2878    0.0    3573.735788  2065.945333       1.119943     2.769816   
2879    0.0    3573.982930  2065.960401       1.011062     2.696217   

      AF3 alpha std  AF3 alpha m  AF3 beta std  AF3 beta m  F7 delta std  ...  \
0          0.526209     3.002088      1.425022    3.302739   3563.803888  ...   
1          1.304186     1.854353      1.366575    2.546458   3563.560922  ...   
2          1.120537     1.958819      0.982433    2.258622   3563.279981  ...   
3          0.629608     2.155876      0.856275    2.233711   3562.787801  ...   
4          0.677526     1.795798      0.927924    1.909810   3562.655091  ...   
...             ...          ...           ...         ...           ...  ...   
2875       0.965369     2.392263      2.582266    3.185588   3565.166724  ...   
2876       0.539180     1.331165      2.533695    2.870270   3565.734750  ...   
2877       0.715012     1.307975      2.261013    2.873613   3567.582880  ...   
2878       0.455408     1.541430      1.782814    3.067384   3567.857997  ...   
2879       1.021707     2.086820      1.922342    2.675613   3568.222662  ...   

      F8 beta std  F8 beta m  AF4 delta std  AF4 delta m  AF4 theta std  \
0       45.468326  72.508750    3701.186330  2182.676835      18.192418   
1       36.551948  66.931186    3725.210509  2180.197439       8.820788   
2       40.754308  66.816547    3724.417296  2176.823208      18.159202   
3       38.074628  63.915386    3725.822160  2177.089059      19.737616   
4       35.357384  64.534645    3723.053978  2167.798335       8.429414   
...           ...        ...            ...          ...            ...   
2875    26.247669  13.320391    3607.467804  2089.263161       1.605773   
2876    26.120266  14.809811    3613.165565  2089.298802       0.643899   
2877    26.513829  16.084048    3615.755534  2094.482958       1.851314   
2878    20.049092  21.248860    3620.821019  2097.450420       5.035767   
2879    19.210888  22.058247    3620.970803  2096.125026       4.120981   

      AF4 theta m  AF4 alpha std  AF4 alpha m  AF4 beta std  AF4 beta m  
0       41.349662      16.004756    42.046467     46.280843   73.565719  
1       38.012788      19.601233    29.431054     38.559351   67.470041  
2       23.612639      14.378291    19.555084     43.210004   67.781924  
3       29.484396      15.793034    25.713513     39.250246   65.031031  
4       26.374975      14.920736    35.675266     33.901687   66.956313  
...           ...            ...          ...           ...         ...  
2875     4.247634       1.649762     2.938868     31.019482   16.648758  
2876     6.903858       1.287563     3.942647     31.546882   17.429113  
2877     5.683580       2.411642     6.355117     32.238063   19.023897  
2878    12.027902       6.441267    14.663681     24.109509   26.468254  
2879    12.124434       7.613556    12.998119     23.635052   26.581116  

[2880 rows x 113 columns]

In [9]:
ESR.loc[3] # it fetches the particular row  loc[row number]

Class               1.000000
AF3 delta std    3567.710021
AF3 delta m      2062.112673
AF3 theta std       2.181775
AF3 theta m         3.610507
                    ...     
AF4 theta m        29.484396
AF4 alpha std      15.793034
AF4 alpha m        25.713513
AF4 beta std       39.250246
AF4 beta m         65.031031
Name: 3, Length: 113, dtype: float64

In [10]:
ESR.loc[3,"AF3 delta std"]

3567.7100207417207

In [11]:
ESR.loc[0:4] # to extract the particular portion of the data set

Class  AF3 delta std  AF3 delta m  AF3 theta std  AF3 theta m  \
0    1.0    3569.164550  2063.892754       1.673726     4.444736   
1    1.0    3568.423670  2063.099248       1.897790     3.728823   
2    1.0    3568.157929  2062.445859       2.798014     2.574504   
3    1.0    3567.710021  2062.112673       2.181775     3.610507   
4    1.0    3565.546124  2063.128867       1.685161     3.384311   

   AF3 alpha std  AF3 alpha m  AF3 beta std  AF3 beta m  F7 delta std  ...  \
0       0.526209     3.002088      1.425022    3.302739   3563.803888  ...   
1       1.304186     1.854353      1.366575    2.546458   3563.560922  ...   
2       1.120537     1.958819      0.982433    2.258622   3563.279981  ...   
3       0.629608     2.155876      0.856275    2.233711   3562.787801  ...   
4       0.677526     1.795798      0.927924    1.909810   3562.655091  ...   

   F8 beta std  F8 beta m  AF4 delta std  AF4 delta m  AF4 theta std  \
0    45.468326  72.508750    3701.186330  2182.676835      18.192418   
1    36.551948  66.931186    3725.210509  2180.197439       8.820788   
2    40.754308  66.816547    3724.417296  2176.823208      18.159202   
3    38.074628  63.915386    3725.822160  2177.089059      19.737616   
4    35.357384  64.534645    3723.053978  2167.798335       8.429414   

   AF4 theta m  AF4 alpha std  AF4 alpha m  AF4 beta std  AF4 beta m  
0    41.349662      16.004756    42.046467     46.280843   73.565719  
1    38.012788      19.601233    29.431054     38.559351   67.470041  
2    23.612639      14.378291    19.555084     43.210004   67.781924  
3    29.484396      15.793034    25.713513     39.250246   65.031031  
4    26.374975      14.920736    35.675266     33.901687   66.956313  

[5 rows x 113 columns]

In [12]:
ESR.loc[0:4,"AF3 delta std"] # to extract only the values of particular  section of the data set and particular coloum

0    3569.164550
1    3568.423670
2    3568.157929
3    3567.710021
4    3565.546124
Name: AF3 delta std, dtype: float64

In [13]:
ESR.loc[0:4,["AF3 delta std","AF3 delta m"]] # to extend the coloums

AF3 delta std  AF3 delta m
0    3569.164550  2063.892754
1    3568.423670  2063.099248
2    3568.157929  2062.445859
3    3567.710021  2062.112673
4    3565.546124  2063.128867

In [14]:
# for the slicing the coloums based on the names
ESR.loc[0:4,"AF3 delta std":"AF3 alpha m"] # to extend the coloums

AF3 delta std  AF3 delta m  AF3 theta std  AF3 theta m  AF3 alpha std  \
0    3569.164550  2063.892754       1.673726     4.444736       0.526209   
1    3568.423670  2063.099248       1.897790     3.728823       1.304186   
2    3568.157929  2062.445859       2.798014     2.574504       1.120537   
3    3567.710021  2062.112673       2.181775     3.610507       0.629608   
4    3565.546124  2063.128867       1.685161     3.384311       0.677526   

   AF3 alpha m  
0     3.002088  
1     1.854353  
2     1.958819  
3     2.155876  
4     1.795798

In [15]:
ESR.iloc[:,1] # iloc[rows,coloums]

0       3569.164550
1       3568.423670
2       3568.157929
3       3567.710021
4       3565.546124
           ...     
2875    3572.820630
2876    3573.915291
2877    3574.326202
2878    3573.735788
2879    3573.982930
Name: AF3 delta std, Length: 2880, dtype: float64

In [16]:
l = [1,2,3,4]
l[:3]

[1, 2, 3]

In [17]:
x = ESR.iloc[:,1:113].values #take the values of the x to train
x
x.shape

(2880, 112)

In [18]:
y = ESR.iloc[:,0].values
y
y.shape
y

array([1., 1., 1., ..., 0., 0., 0.])

In [19]:
from sklearn.model_selection import train_test_split, cross_val_score
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size = 0.4,random_state=0)

In [20]:
X_train

array([[3.57117491e+03, 2.06436255e+03, 1.51874602e+00, ...,
        2.41254298e+01, 2.12617309e+01, 3.87207238e+01],
       [3.57415462e+03, 2.06522948e+03, 1.52573778e+00, ...,
        7.12421924e+00, 3.53609399e+01, 1.98045560e+01],
       [3.57184269e+03, 2.06505550e+03, 1.31052908e+00, ...,
        4.03435113e+01, 3.39436414e+01, 5.29638116e+01],
       ...,
       [3.57486351e+03, 2.06590684e+03, 1.35336738e+00, ...,
        8.68251156e+00, 3.55012520e+01, 2.96547964e+01],
       [3.57287323e+03, 2.06399630e+03, 2.04662830e+00, ...,
        7.95205727e+00, 3.35529189e+01, 1.91060034e+01],
       [3.57318626e+03, 2.06445202e+03, 4.48625441e-01, ...,
        1.69092966e+01, 2.30460812e+01, 3.06892648e+01]])

In [21]:
X_test

array([[3.57266895e+03, 2.06442576e+03, 7.00105988e-01, ...,
        8.85405014e+00, 5.70580449e+01, 3.30533653e+01],
       [3.57544765e+03, 2.06597371e+03, 7.61767438e-01, ...,
        1.03058434e+01, 3.92314311e+01, 2.71089612e+01],
       [3.57374340e+03, 2.06473700e+03, 6.81163874e-01, ...,
        1.15353676e+01, 3.39159994e+01, 2.31209811e+01],
       ...,
       [3.57241940e+03, 2.06390025e+03, 4.64999250e-01, ...,
        3.06334966e+01, 3.94139421e+01, 4.34565856e+01],
       [3.57331915e+03, 2.06448907e+03, 5.80886485e-01, ...,
        7.52830763e+00, 3.57951577e+01, 1.96736949e+01],
       [3.57443299e+03, 2.06563445e+03, 7.57122535e-01, ...,
        7.99928784e+00, 3.26315537e+01, 1.85151341e+01]])

In [22]:
y_test

array([1., 0., 1., ..., 0., 2., 2.])

In [23]:
y_train

array([1., 2., 1., ..., 2., 2., 0.])

In [24]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)


# logistic regression 

In [25]:
from sklearn.linear_model import LogisticRegression
clf1 = LogisticRegression()


clf1.fit(X_train, y_train)
y_pred_log_reg = clf1.predict(X_test)
acc_log_reg = round(clf1.score(X_train, y_train) * 100, 2)
print (str(acc_log_reg) + ' %')

# Set regularization rate
reg = 1
# train a logistic regression model on the training set
model0 = LogisticRegression(C=0.1/reg, solver="liblinear").fit(X_train, y_train)
print (model0)

predictions0 = model0.predict(X_test)
print('Predicted labels: ', predictions0)
print('Actual labels:    ' ,y_test)


from sklearn.metrics import accuracy_score
print('Accuracy:', accuracy_score(y_test, predictions0)*100,'%')




C:\Users\USER\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


69.33 %
LogisticRegression(C=0.1, solver='liblinear')
Predicted labels:  [0. 0. 0. ... 0. 2. 2.]
Actual labels:     [1. 0. 1. ... 0. 2. 2.]
Accuracy: 59.201388888888886 %


# support vector machines

In [26]:
#Support Vector Machine (SVM)
from sklearn.svm import SVC
clf2 = SVC()
clf2.fit(X_train, y_train)
y_pred_svc = clf2.predict(X_test)
acc_svc = round(clf2.score(X_train, y_train) * 100, 2)
print ('Accuracy due to svm',str(acc_svc) + '%')
#acc_svc =str(acc_svc )

# Set regularization rate
reg = 1
# train a support vector machine model on the training set
svm = SVC(kernel= 'linear', random_state=1, C=0.1)
svm.fit(X_train, y_train)
print (svm)

predictions1 = svm.predict(X_test)
print('Predicted labels: ', predictions1)
print('Actual labels:    ' ,y_test)

from sklearn.metrics import accuracy_score
print('Accuracy:', accuracy_score(y_test, predictions1)*100,'%')


Accuracy due to svm 88.95%
SVC(C=0.1, kernel='linear', random_state=1)
Predicted labels:  [0. 0. 0. ... 0. 0. 2.]
Actual labels:     [1. 0. 1. ... 0. 2. 2.]
Accuracy: 59.635416666666664 %


# k nearest neighbors

In [27]:
#k-Nearest Neighbors
from sklearn.neighbors import KNeighborsClassifier
clf3 = KNeighborsClassifier()
clf3.fit(X_train, y_train)
y_pred_knn = clf3.predict(X_test)
acc_knn = round(clf3.score(X_train, y_train) * 100, 2)
print ('accuracy due to k-nearest neighbors',str(acc_knn)+'%')

from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
classifier.fit(X_train, y_train)

predictions2 =classifier.predict(X_test)
print('Predicted labels: ', predictions2)
print('Actual labels:    ' ,y_test)

from sklearn.metrics import accuracy_score
print('Accuracy:', accuracy_score(y_test, predictions2)*100,'%')


accuracy due to k-nearest neighbors 91.78%
Predicted labels:  [0. 0. 0. ... 0. 2. 1.]
Actual labels:     [1. 0. 1. ... 0. 2. 2.]
Accuracy: 82.29166666666666 %


# pickle model linear regression

In [28]:
#linear regression model 

import pickle
with open ('liner_model','wb') as f:
    pickle.dump(clf1,f)
    
with open('liner_model','rb') as f:
    np = pickle.load(f)
    
np.predict(X_test)



array([0., 0., 0., ..., 0., 2., 2.])

# joblib  model linear regression

In [29]:
import joblib

joblib.dump(clf1,'linearmodel_joblib')
lin = joblib.load('linearmodel_joblib')
lin.predict(X_test)





array([0., 0., 0., ..., 0., 2., 2.])

# pickle model support vector machine

In [30]:
import pickle
with open ('svm_model','wb') as f1:
    pickle.dump(clf2,f1)
    
with open('svm_model','rb') as f1:
    np = pickle.load(f1)
    
np.predict(X_test)


array([0., 0., 0., ..., 0., 2., 2.])

# joblib model support vector machines

In [31]:
import joblib

joblib.dump(clf2,'svmmodel_joblib')
svm = joblib.load('svmmodel_joblib')
svm.predict(X_test)




array([0., 0., 0., ..., 0., 2., 2.])

# pickle model k nearest neighbour

In [32]:


import pickle
with open ('knn_model','wb') as f:
    pickle.dump(clf3,f)
    
with open('knn_model','rb') as f:
    np = pickle.load(f)
    
np.predict(X_test)


array([0., 0., 0., ..., 0., 2., 1.])

# joblib model for k nearest neighbour

In [33]:
import joblib

joblib.dump(clf3,'knnmodel_joblib')
svm = joblib.load('knnmodel_joblib')
svm.predict(X_test)




array([0., 0., 0., ..., 0., 2., 1.])